# Site settings
title: Karmak Unity
email: sales@karmak.com
description: > # this means to ignore newlines until "baseurl:"
  Unity provides a single point of access where outside/third party systems can effectively communicate with Fusion using a set of pre-defined APIs.  Unity will both simplify and accelerate the integration process – allowing you to operate at the speed of business.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings

